python train.py \
--seed 42 \
--output_dir ./output \
--do_train \
--logging_strategy epoch \
--do_eval \
--evaluation_strategy epoch \
--save_strategy epoch \
--per_device_train_batch_size 16 \
--per_device_eval_batch_size 16 \
--num_train_epochs 3 \